version: '3'
services:
  app:
    container_name: app10
    image: app:0.0.1
    build: ./docker/app
    volumes:
      - .:/var/www/src
    depends_on:
      - db
  nginx:
    image: nginx:1.22.1
    build: ./docker/nginx
    container_name: nginx10
    ports:
      - 8001:80 
    volumes:
      - .:/var/www/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    image: mysql:8.0.32
    container_name: db10
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel10
      MYSQL_USER: mysql_use
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo' 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:  
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
# コンテナ起動時に下記のフォルダ内の .sql, .sh, .sql.gz を読み込み実行することができる
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 33067:3306